# Generated by Django 2.1.7 on 2019-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Author name.')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Book name')),
                ('isbn', models.CharField(max_length=14, verbose_name="Book's ISBN")),
                ('country', models.CharField(max_length=256, verbose_name='Country')),
                ('number_of_pages', models.IntegerField(verbose_name='Number of pages in book.')),
                ('publisher', models.CharField(max_length=256, verbose_name='Publisher of book.')),
                ('release_date', models.CharField(max_length=256, verbose_name='Release date of book.')),
                ('authors', models.ManyToManyField(to='book.Author', verbose_name="Book's authors names.")),
            ],
        ),
    ]
